server:
  port: 8080
  servlet:
    context-path: /POD_BookingSystem

spring:
  datasource:
    url: "jdbc:mysql://14.225.206.250:3306/POD_BookingSystem"
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.example.com
    port: 587
    username: haxuankhang194@gmail.com
    password: riukttjkajzztrra
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
jwt:
  signKey: "XyoNeBIfTwb3rCdDFFnzcXQHcyaX7G+y/nTn5loDeYWuf4hPFMsfwEfjsM5qGz+i"
  valid-duration: 3600
  refreshable-duration: 120

logging:
  level:
    root: INFO
    com.example.identity_service: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
