server:
  port: 8080
  servlet:
    context-path: /POD_BookingSystem
#14.225.206.250
spring:
  datasource:
    url: "jdbc:mysql://14.225.206.250:3306/POD_BookingSystem"
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.example.com
    port: 587
    username: haxuankhang194@gmail.com
    password: riukttjkajzztrra
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
jwt:
  signKey: "XyoNeBIfTwb3rCdDFFnzcXQHcyaX7G+y/nTn5loDeYWuf4hPFMsfwEfjsM5qGz+i"
  valid-duration: 3600
  refreshable-duration: 120

logging:
  level:
    root: INFO
    com.example.identity_service: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

twilio:
  account_sid: ACb64fbab279b730b3ccf1980937c6db19
  auth_token: 4246a8f66efb5b11ba5358d528a827c8
  verify_sid: VA3db9a978e959f96b9b8a9e4684675398
  verified-number: "+84357732955"

sms:
  url : "https://api.speedsms.vn/index.php"
  token: rey0QssUXchxOL9p3u3dkp1LVah8VVYP